[package]
name = "tari_validator_node"
version = "0.1.0"
authors = ["The Tari Development Community"]
description = "The tari validation node implementation"
repository = "https://github.com/tari-labs/validator-node"
license = "BSD-3-Clause"
edition = "2018"

[dependencies]
tari_common = "^0.0"
tari_comms = "^0.0"
tari_comms_dht = "^0.0"
tari_core = "^0.0"
tari_p2p = "^0.0"
tari_service_framework = "^0.0"
tari_shutdown = "^0.0"
tari_mmr = "^0.0"
tari_wallet = "^0.0"
tari_broadcast_channel = "^0.1"

config = "0.10"
structopt = "0.3"
serde = { version = "1", features = ["derive"] }
log = "0.4"