[package]
name = "tari_validator_node"
version = "0.1.0"
authors = ["The Tari Development Community"]
description = "The tari validation node implementation"
repository = "https://github.com/tari-labs/validator-node"
license = "BSD-3-Clause"
edition = "2018"

[dependencies]
tari_common = "^0.1"
tari_wallet = "^0.1"
tari_crypto = "^0.3"

structopt = { version = "0.3", default_features = false }
serde = { version = "1", features = ["derive"] }
log = "0.4"
anyhow = "1"
thiserror = "1"
deadpool-postgres = { version = "0.5.5", features = ["config"] }
tokio-postgres = { version = "0.5.3", features = ["with-uuid-0_8", "with-chrono-0_4"] }
refinery = { version = "0.2", features = ["tokio-postgres"]}
actix-web = "2.0.0"
actix-rt = "1.1.0"
config = { version = "0.9.3", default_features = false }
tokio-pg-mapper = { version = "0.1.7", features = ["derive"] }
uuid = { version = "0.8", features = ["serde"] }
chrono = "0.4"

[dev-dependencies]
lazy_static = "1.4"
dotenv = "0.15"
