[package]
name = "tari_validator_node"
version = "0.1.0"
authors = ["The Tari Development Community"]
description = "The tari validation node implementation"
repository = "https://github.com/tari-labs/validator-node"
license = "BSD-3-Clause"
edition = "2018"

[dependencies]
tari_common = "^0.1"
tari_comms = "^0.0"
tari_comms_dht = "^0.0"
tari_core = "^0.0"
tari_p2p = "^0.0"
tari_service_framework = "^0.0"
tari_shutdown = "^0.0"
tari_mmr = "^0.0"
tari_wallet = "^0.0"
tari_broadcast_channel = "^0.1"

structopt = { version = "0.3", default_features = false }
serde = { version = "1", features = ["derive"] }
log = "0.4"
anyhow = "1"
deadpool-postgres = { version = "0.5.5", features = ["config"] }
tokio-postgres = "0.5.3"
refinery = { version = "0.2", features = ["tokio-postgres"]}
actix-web = "2.0.0"
actix-rt = "1.1.0"
config = { version = "0.9.3", default_features = false }

[dev-dependencies]
lazy_static = "1.4"
